opt_in_rules:
  - closure_spacing
  - function_default_parameter_at_end
  - fatal_error_message
  - unused_private_declaration
  - convenience_type

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

identifier_name:
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 45
    error: 60

type_name:
  min_length:
    warning: 0
    error: 0
  max_length:
    warning: 45
    error: 60

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

type_body_length:
  warning: 200
  error: 400

function_body_length:
  warning: 40
  error: 80

custom_rules:
  force_unwrapping_warning:
    included: "*.swift"
    name: "Force Unwrapping Detected"
    regex: "![^=]"
    message: "Avoid using force unwrapping (!) unless absolutely necessary."
    severity: warning

reporter: "xcode"
