name: SwiftUICoordinator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      PROJECT: Example/SwiftUICoordinatorExample/SwiftUICoordinatorExample.xcodeproj
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
      SCHEME: SwiftUICoordinator
      DESTINATION: platform=iOS Simulator,name=iPhone 16 Pro
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer

    - name: Clear Derived Data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint

    # - name: List Available Simulators
    #   run: xcrun simctl list devices

    - name: Run tests
      run: xcodebuild clean test -project "SwiftUICoordinatorExample.xcodeproj" -scheme "SwiftUICoordinator" -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest"

    # - name: Build and test
    #   run: |
    #     swift package update
    #     xcodebuild clean test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION"
