name: SwiftUICoordinator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    env:
      XCODE_DIR: /Applications/Xcode_16.2.app/Contents/Developer
      SCHEME: SwiftUICoordinator
      DESTINATION: platform=iOS Simulator,name=iPhone 16 Pro
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select --switch $XCODE_DIR

    - name: Clear Derived Data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint

    - name: Test
      run: |
        swift package update
        xcodebuild clean test -scheme $SCHEME -destination "$DESTINATION" -skipTestPlan
